### ISSUE TITLE
Remove the secondary footer with sponsor logos

### ISSUE THREAD

**Issue by heymosef** [womenandcolor/women-and-color-static#53]
Our sponsorship with TribalScale and Wealthsimple is now over. Given we don't have any new Premier Partners at the moment, there is no need for the secondary footer with logos in it.

**Comment by AV-room** [comment]
I can tackle this.

**Comment by heymosef** [comment]
@AV-room Thank you! Also, who is this? 👀

**Comment by AV-room** [comment]
@heymosef I'm a web dev from Australia. As a woman in tech, I would love to contribute to this project :)

**Comment by heymosef** [comment]
Thanks @AV-room!

Please go ahead when you get a chance.

**Comment by AV-room** [comment]
@heymosef - @jordonmckoy has beat me to the punch! Looks like this issue can be closed now.

**Comment by heymosef** [comment]
Sorry An! I'm creating a few more smaller tickets if you're able to contribute. <3
